jobs:
  - job: SonarQubeAnalysis_python
    displayName: 🛡️Sonarqube Analysis🛡️🚦
    dependsOn: initJob
    condition: not(eq(variables[dependencies.initJob.outputs['init.repoName']],'true'))
    steps:
      - template: main.yml
        parameters:
          workPath: ${{ parameters.workPath }}
          testExclusion: "**/tests/**, **/__init__.py"
          testInclusions: "**/tests/**/test*"
          repoName: $(Build.Repository.Name)
