jobs:
  - job: SonarQubeAnalysis_node
    displayName: 🛡️Sonarqube Analysis🛡️🚦
    dependsOn: initJob
    condition: not(eq(variables[dependencies.initJob.outputs['init.repoName']],'true'))
    steps:
      - template: main.yml
        parameters:
          workPath: ${{ parameters.workPath }}
          testExclusion: "**/coverage/**, **/node_modules/**, **/__mocks__/**, **/*.config.js, **/tests/**"
          testInclusions: "**/tests/**/*.test.*"
          repoName: $(Build.Repository.Name)
